#!/bin/bash
# Build Script - Compile Each Contract Individually
# Generated by Immunefi Instascope

set -e

echo "Building 2 contracts individually..."
echo ""

echo "Building Splitter (contract_Splitter_03fd)"
FOUNDRY_PROFILE=contract_Splitter_03fd forge build || {
  echo "❌ Failed to build Splitter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Splitter_03fd forge build"
}
echo "✅ Built Splitter"
echo ""

echo "Building Splitter (contract_Splitter_3234)"
FOUNDRY_PROFILE=contract_Splitter_3234 forge build || {
  echo "❌ Failed to build Splitter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_Splitter_3234 forge build"
}
echo "✅ Built Splitter"
echo ""

echo "================================"
echo "Build complete - each contract compiled independently"
echo "================================"
